# Generated by Django 3.2.4 on 2021-07-01 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='assignee_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_id', to='softdesk.users'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='author_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to='softdesk.users'),
        ),
    ]
