# Generated by Django 3.2.4 on 2021-07-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0003_auto_20210702_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
