# Generated by Django 3.2.4 on 2021-07-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0005_auto_20210703_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author_user_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='issue_id',
            new_name='issue',
        ),
        migrations.RenameField(
            model_name='contributors',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='contributors',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='assignee_user_id',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='author_user_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='author_user_id',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='contributors',
            name='permission',
            field=models.CharField(choices=[('author', 'Author'), ('contributor', 'Contributor')], max_length=128),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[('project', 'Project'), ('product', 'Product'), ('application', 'Application')], max_length=128),
        ),
    ]
