# Generated by Django 3.2.4 on 2021-07-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0006_auto_20210706_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='author',
        ),
        migrations.AlterField(
            model_name='contributors',
            name='permission',
            field=models.CharField(choices=[('author', 'Author'), ('contributor', 'Contributor')], default='contributor', max_length=128),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(default='role', max_length=128),
        ),
    ]
